openapi: 3.0.0
info:
  title: Armstrong Number API
  version: 1.0.0
paths:
  /api/v1/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        201:
          description: User created successfully